<a href="https://colab.research.google.com/github/d12eek/ANN-And-DL-Lab-24mcs005/blob/main/MLP_Optimizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.datasets import make_regression
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange, tqdm

#TensorFlow and Keras Libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import torch
from torchvision import transforms
from tensorflow.keras.utils import to_categorical
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os

# Hiding the warnings
import warnings
warnings.filterwarnings('ignore')

# Extra Libraries
import copy
import random
import time

In [3]:
file_path = '/content/house-prices.csv'
df = pd.read_csv(file_path)

In [4]:
df.shape

(128, 8)

In [5]:
df.head()

   Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Home          128 non-null    int64
 1   Price         128 non-null    int64
 2   SqFt          128 non-null    int64
 3   Bedrooms      128 non-null    int64
 4   Bathrooms     128 non-null    int64
 5   Offers        128 non-null    int64
 6   Brick         128 non-null    object
 7   Neighborhood  128 non-null    object
dtypes: int64(6), object(2)
memory usage: 8.1+ KB

In [7]:
df.isna().sum()

Home            0
Price           0
SqFt            0
Bedrooms        0
Bathrooms       0
Offers          0
Brick           0
Neighborhood    0
dtype: int64

In [8]:
cat_col = []
for i in df.columns:
    if df[i].dtype == 'O':
        cat_col.append(i)

cat_col

['Brick', 'Neighborhood']

In [9]:
df['Brick'].value_counts()

Brick
No     86
Yes    42
Name: count, dtype: int64

In [10]:
df[cat_col].nunique()

Brick           2
Neighborhood    3
dtype: int64

In [11]:
le1 = LabelEncoder()
df['Brick'] = le1.fit_transform(df['Brick'])
df['Brick'].unique()

le2 = LabelEncoder()
df['Neighborhood'] = le2.fit_transform(df['Neighborhood'])
df['Neighborhood'].unique()

array([0, 1, 2])

In [12]:
df.drop('Home',axis=1,inplace=True)

In [13]:
sc1 = MinMaxScaler()
df[['Price']] = sc1.fit_transform(df[['Price']])

sc2 = MinMaxScaler()
df[['SqFt']] = sc2.fit_transform(df[['SqFt']])

In [14]:
df['Price'] = round(df['Price'],2)
df['SqFt'] = round(df['SqFt'],2)

In [15]:
X = df.drop('Brick',axis=1)
y = df['Brick']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (85, 6)
X_test shape :  (43, 6)
y_train shape :  (85,)
y_test shape :  (43,)

In [17]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(45,activation='relu',input_dim = 6))
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.Dense(15,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [18]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=100)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - BinaryAccuracy: 0.7416 - loss: 0.6557
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7065 - loss: 0.6325
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7182 - loss: 0.6191
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7221 - loss: 0.5965
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7299 - loss: 0.5798
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.6830 - loss: 0.6193
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7182 - loss: 0.5845
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7534 - loss: 0.5560
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7143 - loss: 0.5738
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.6948 - loss: 0.6148
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7182 - loss: 0.5878
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7377 - loss: 0.5668
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.6791 - loss: 0.6066
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7612 - loss: 0.5298
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7182 - loss: 0.5726
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7182 - loss: 0.5765
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.6869 - loss: 0.5912
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7221 - loss: 0.5644
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7299 - loss: 0.5656
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7377 - loss: 0.5558
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7143 - loss: 0.5736
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7534 - loss: 0.5366
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.7455 - loss: 0.5392
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.6909 - loss: 0.5874
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7494 - loss: 0.5501
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7651 - loss: 0.5285
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.7221 - loss: 0.5609
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7338 - loss: 0.5428
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7163 - loss: 0.5634
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7045 - loss: 0.5847
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7280 - loss: 0.5629
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.6752 - loss: 0.5934
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7065 - loss: 0.5655
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7631 - loss: 0.5200
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.6948 - loss: 0.5690
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7534 - loss: 0.5288
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7221 - loss: 0.5522
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7260 - loss: 0.5405
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7573 - loss: 0.5197
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.6948 - loss: 0.5633
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7788 - loss: 0.5165
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7280 - loss: 0.5568
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7280 - loss: 0.5366
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7514 - loss: 0.5350
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7397 - loss: 0.5440
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7319 - loss: 0.5408
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7866 - loss: 0.4832
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7397 - loss: 0.5470
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7534 - loss: 0.5429
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7534 - loss: 0.5440
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7574 - loss: 0.5582
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7651 - loss: 0.5144
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7339 - loss: 0.5459
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7866 - loss: 0.5044
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7671 - loss: 0.5313
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7476 - loss: 0.5298
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.7671 - loss: 0.5493
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7828 - loss: 0.5247
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7965 - loss: 0.5284
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7808 - loss: 0.5212
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8003 - loss: 0.5023
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.7476 - loss: 0.5130
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7593 - loss: 0.5235
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7476 - loss: 0.5259
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8004 - loss: 0.5113
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8004 - loss: 0.4984
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8121 - loss: 0.4820
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7711 - loss: 0.5491
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7984 - loss: 0.4987
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7945 - loss: 0.5102
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7789 - loss: 0.5312
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7789 - loss: 0.5341
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7984 - loss: 0.5008
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7945 - loss: 0.5060
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8180 - loss: 0.4922
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8023 - loss: 0.5214
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7945 - loss: 0.4987
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7984 - loss: 0.5075
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7789 - loss: 0.5149
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7906 - loss: 0.4993
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7789 - loss: 0.5331
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8258 - loss: 0.4765
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7769 - loss: 0.5234
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7847 - loss: 0.5094
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8023 - loss: 0.4878
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8219 - loss: 0.4859
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8102 - loss: 0.4975
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7867 - loss: 0.5077
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8512 - loss: 0.4533
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8004 - loss: 0.5130
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7848 - loss: 0.5031
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8062 - loss: 0.4642
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - BinaryAccuracy: 0.7828 - loss: 0.4978
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8278 - loss: 0.5003
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8102 - loss: 0.4566
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8102 - loss: 0.4747
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8082 - loss: 0.4780
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8082 - loss: 0.4677
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8278 - loss: 0.4542
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8082 - loss: 0.4937
Training time: 7.53 seconds

In [19]:
start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - BinaryAccuracy: 0.6010 - loss: 0.6326
Testing time: 0.28 seconds

In [20]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
(43, 1)
(43,)

In [21]:
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6046511627906976
Confusion Matrix:
 [[24  1]
 [16  2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.96      0.74        25
           1       0.67      0.11      0.19        18

    accuracy                           0.60        43
   macro avg       0.63      0.54      0.46        43
weighted avg       0.63      0.60      0.51        43

In [22]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='rmsprop', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=100)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - BinaryAccuracy: 0.8278 - loss: 0.4772
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - BinaryAccuracy: 0.8160 - loss: 0.4597
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8102 - loss: 0.5012
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8063 - loss: 0.4824
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8043 - loss: 0.4936
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8082 - loss: 0.4775
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7770 - loss: 0.4766
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8180 - loss: 0.4720
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8082 - loss: 0.4901
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7887 - loss: 0.4892
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8415 - loss: 0.4475
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8219 - loss: 0.4582
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8551 - loss: 0.4129
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7926 - loss: 0.4902
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8258 - loss: 0.4720
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8336 - loss: 0.4377
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8024 - loss: 0.4834
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8161 - loss: 0.4886
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8258 - loss: 0.4440
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8239 - loss: 0.4846
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - BinaryAccuracy: 0.8473 - loss: 0.4432
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7829 - loss: 0.5101
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8356 - loss: 0.4557
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8258 - loss: 0.4337
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8336 - loss: 0.4614
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8141 - loss: 0.4632
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8239 - loss: 0.4659
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8473 - loss: 0.4438
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8415 - loss: 0.4515
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8258 - loss: 0.4450
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8219 - loss: 0.4734
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8161 - loss: 0.4882
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8219 - loss: 0.4549
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8512 - loss: 0.4385
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8278 - loss: 0.4445
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8356 - loss: 0.4514
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8356 - loss: 0.4555
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8336 - loss: 0.4222
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8473 - loss: 0.4370
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8356 - loss: 0.4215
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8161 - loss: 0.4368
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8063 - loss: 0.4593
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8258 - loss: 0.4714
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8395 - loss: 0.4218
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8122 - loss: 0.4681
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8141 - loss: 0.4681
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8415 - loss: 0.3984
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8512 - loss: 0.4263
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8102 - loss: 0.4325
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8610 - loss: 0.3969
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8336 - loss: 0.4325
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8356 - loss: 0.4453
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8473 - loss: 0.4144
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8551 - loss: 0.4066
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8434 - loss: 0.4060
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8473 - loss: 0.4088
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8297 - loss: 0.4348
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8356 - loss: 0.4617
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8083 - loss: 0.4624
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8512 - loss: 0.4104
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8434 - loss: 0.4167
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8395 - loss: 0.4084
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8591 - loss: 0.4037
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8317 - loss: 0.4409
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8551 - loss: 0.3903
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8727 - loss: 0.3962
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8376 - loss: 0.4161
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8239 - loss: 0.4183
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8395 - loss: 0.4313
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8395 - loss: 0.4089
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8356 - loss: 0.4357
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8356 - loss: 0.4012
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8650 - loss: 0.4036
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8200 - loss: 0.4343
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.8356 - loss: 0.4168
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8337 - loss: 0.4106
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8220 - loss: 0.4226
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8259 - loss: 0.4372
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8434 - loss: 0.3982
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8337 - loss: 0.4137
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8885 - loss: 0.4148
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8337 - loss: 0.4229
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8395 - loss: 0.4247
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8317 - loss: 0.4157
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8513 - loss: 0.4321
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8513 - loss: 0.4076
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8239 - loss: 0.4162
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8356 - loss: 0.4013
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8396 - loss: 0.4220
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8259 - loss: 0.4385
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8337 - loss: 0.4135
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8396 - loss: 0.4191
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8200 - loss: 0.4276
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8513 - loss: 0.4033
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8239 - loss: 0.4292
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8747 - loss: 0.3855
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8435 - loss: 0.3979
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8532 - loss: 0.3856
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8688 - loss: 0.3678
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8806 - loss: 0.4114
Training time: 6.98 seconds

In [23]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
(43, 1)
(43,)

In [24]:
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6511627906976745
Confusion Matrix:
 [[25  0]
 [15  3]]
Classification Report:
               precision    recall  f1-score   support

           0       0.62      1.00      0.77        25
           1       1.00      0.17      0.29        18

    accuracy                           0.65        43
   macro avg       0.81      0.58      0.53        43
weighted avg       0.78      0.65      0.57        43

In [25]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adagrad', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=100)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - BinaryAccuracy: 0.8591 - loss: 0.3723
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - BinaryAccuracy: 0.8122 - loss: 0.4669
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - BinaryAccuracy: 0.8435 - loss: 0.4255
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8727 - loss: 0.3682
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8806 - loss: 0.3291
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8630 - loss: 0.4082
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8571 - loss: 0.3879
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8513 - loss: 0.3936
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8591 - loss: 0.3814
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.8474 - loss: 0.3973
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8864 - loss: 0.3623
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8591 - loss: 0.3935
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8513 - loss: 0.3906
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8435 - loss: 0.4001
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8396 - loss: 0.3910
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8630 - loss: 0.3811
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8200 - loss: 0.4337
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8513 - loss: 0.4081
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8786 - loss: 0.3613
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8630 - loss: 0.3709
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8708 - loss: 0.3896
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8435 - loss: 0.4194
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8396 - loss: 0.3781
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8786 - loss: 0.3572
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8689 - loss: 0.3793
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8278 - loss: 0.4028
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.8552 - loss: 0.3982
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8552 - loss: 0.3946
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8708 - loss: 0.3556
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8435 - loss: 0.3948
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8396 - loss: 0.3993
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8591 - loss: 0.3838
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8786 - loss: 0.3584
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8591 - loss: 0.3659
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8689 - loss: 0.4324
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8572 - loss: 0.4059
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8552 - loss: 0.3836
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8708 - loss: 0.3680
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8689 - loss: 0.3834
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8533 - loss: 0.4189
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8903 - loss: 0.3665
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8630 - loss: 0.3725
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8689 - loss: 0.3694
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8435 - loss: 0.4039
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8435 - loss: 0.4177
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8630 - loss: 0.3826
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8552 - loss: 0.3980
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8494 - loss: 0.3998
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8533 - loss: 0.4467
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8786 - loss: 0.3616
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8747 - loss: 0.3539
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8689 - loss: 0.3973
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8474 - loss: 0.4030
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8689 - loss: 0.3819
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8669 - loss: 0.3780
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8689 - loss: 0.3891
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8708 - loss: 0.3754
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8669 - loss: 0.3679
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8864 - loss: 0.3400
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8689 - loss: 0.3814
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8806 - loss: 0.3671
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8845 - loss: 0.3736
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8669 - loss: 0.3670
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8708 - loss: 0.3713
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8669 - loss: 0.3835
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8708 - loss: 0.4151
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8689 - loss: 0.3818
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8494 - loss: 0.4016
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8806 - loss: 0.3654
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8611 - loss: 0.3998
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8786 - loss: 0.3590
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8923 - loss: 0.3559
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8630 - loss: 0.3706
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8591 - loss: 0.3729
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8845 - loss: 0.3746
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8689 - loss: 0.4010
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8806 - loss: 0.3606
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8728 - loss: 0.3848
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8728 - loss: 0.3942
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8650 - loss: 0.3939
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.8572 - loss: 0.3805
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.8864 - loss: 0.3415
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8767 - loss: 0.3824
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8513 - loss: 0.3898
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8630 - loss: 0.3809
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8494 - loss: 0.4172
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8435 - loss: 0.4165
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8962 - loss: 0.3676
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8650 - loss: 0.3745
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8845 - loss: 0.3584
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8611 - loss: 0.3992
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8884 - loss: 0.3688
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8552 - loss: 0.4038
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8572 - loss: 0.3789
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8572 - loss: 0.3955
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8494 - loss: 0.4024
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8591 - loss: 0.3706
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8767 - loss: 0.3853
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - BinaryAccuracy: 0.8728 - loss: 0.3798
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.8767 - loss: 0.3671
Training time: 7.47 seconds

In [26]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7e458cdcc040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step

WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7e458cdcc040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
(43, 1)
(43,)

In [27]:
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6511627906976745
Confusion Matrix:
 [[23  2]
 [13  5]]
Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.92      0.75        25
           1       0.71      0.28      0.40        18

    accuracy                           0.65        43
   macro avg       0.68      0.60      0.58        43
weighted avg       0.67      0.65      0.61        43